### ISSUE TITLE
Submission system and process

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/climate-informatics-2024#11]
### Summary Sentence

This conference has previously used [Microsoft Conference Management Toolkit (CMT)](https://cmt3.research.microsoft.com/About) to manage submissions. The tool was effective, so the org committee are happy to use this again.

### What needs to be done?

Douglas to set up and communicate back on any required resources/decisions from the committee

### Who can help?

Douglas

---

### Update after the issue was opened

[Add details]

**Comment by geo-rao** [comment]
CMT system is approved for CI2024 - need to determine submission types.

Previous submission tracks include (see [CI 2023](https://cambridge-iccs.github.io/climate-informatics-2023/submission))
- Extended abstracts (2 pages maximum)
- Full paper (8 pages maximum)

Reviewers expressed hard to evaluate the value of extended abstracts. This needs to be addressed by adding instructions for authors what information to include in the extended abstracts.

**Comment by cassgvp** [comment]
Thanks @geo-rao for linking the 2023 guidelines! Do you have a link for 2024 CMT? 

And to confirm (@scotthosking @geo-rao ) we're going to ask people to identify the [type of submission as aligned with EDS](https://www.cambridge.org/core/journals/environmental-data-science/information/author-instructions/preparing-your-materials), i.e:

- **Application papers**: Research progress, or tackling a real-world problem, in an environmental field, enabled by data science. For example, AI or data science could be used for understanding of environmental processes, or improving forecasting tools.
- **Methods papers**: Novel data science methodology inspired by an environmental problem or application. Typically the methodology should be demonstrated in one or more environmental applications.
- **Data papers** that describe in a structured way, with a short narrative and accompanying metadata, important and re-usable environmental data sets that reside in publicly accessible repositories. These papers promote data transparency and data re-use.
- **Survey papers**: providing a systematic overview of a method, tool or approach, or a field or subfield that is relevant to environmental data science.
- **Position papers**: examples include but are not limited to: a) providing an authoritative, personal view on the uptake or obstacles to AI and data science approaches for environmental problems, or b) exploring issues related to the use of environmental data, including ethical, legal and policy issues, as well as data standards, protocols and services.

Perhaps we could ask for submissions to include an impact statement (as in EDS), to assist reviewing? 
> Impact statement: Beneath the abstract authors must provide a 120-word impact that summarises the significance of their work for a broad audience. This will be published in the article itself.

Do you also want to include something like "extended abstracts should follow an introduction, method, results and discussion format" or does it need more than that?

**Comment by cassgvp** [comment]
Are authors asked whether they wish to be considered for a talk or a poster? Or does the programme committee decide this?

**Comment by cassgvp** [comment]
Closing as the system is live and accepting submissions :)
